name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-and-test:
    permissions:
        packages: read
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - run: |
          cp .env.template .env
          echo GITHUB_USER=$GITHUB_USER >> .env
          echo GITHUB_TOKEN=$GITHUB_TOKEN >> .env
      - name: Assemble
        run: ./gradlew :missionmodel:build
      - name: Run Unit Tests
        run: ./gradlew :missionmodel:test
